external_components:
  - source: github://idlezombie/esphome
    components: [ mpu6050_custom ]

globals:
  - id: mpu6050
    type: MPU6050Custom*
    restore_value: no
    initial_value: 'nullptr'

sensor:
  - platform: template
    id: mpu6050_initializer
    internal: true
    lambda: |-
      if (id(mpu6050) == nullptr) {
        auto mpu = new MPU6050Custom();
        id(mpu6050) = mpu;
        App.register_component(mpu);
      }
      return {};
    update_interval: never

  - platform: template
    name: "MPU6050 Accel X"
    lambda: |-
      return id(mpu6050)->accel_x->state;

  - platform: template
    name: "MPU6050 Accel Y"
    lambda: |-
      return id(mpu6050)->accel_y->state;

  - platform: template
    name: "MPU6050 Accel Z"
    lambda: |-
      return id(mpu6050)->accel_z->state;

  - platform: template
    name: "MPU6050 Gyro X"
    lambda: |-
      return id(mpu6050)->gyro_x->state;

  - platform: template
    name: "MPU6050 Gyro Y"
    lambda: |-
      return id(mpu6050)->gyro_y->state;

  - platform: template
    name: "MPU6050 Gyro Z"
    lambda: |-
      return id(mpu6050)->gyro_z->state;

  - platform: template
    name: "MPU6050 Temperature"
    lambda: |-
      return id(mpu6050)->temperature->state;

  - platform: template
    name: "MPU6050 Angle X"
    lambda: |-
      return id(mpu6050)->angle_x->state;

  - platform: template
    name: "MPU6050 Angle Y"
    lambda: |-
      return id(mpu6050)->angle_y->state;

button:
  - platform: template
    name: "MPU6050 Recalibrate"
    on_press:
      then:
        - lambda: |-
            id(mpu6050)->do_recalibrate();

light:
  - platform: esp32_rmt_led_strip
    id: esp32_led
    name: "Light"
    entity_category: config
    pin: GPIO8
    chipset: ws2812
    rgb_order: RGB
    num_leds: 1
    restore_mode: RESTORE_DEFAULT_OFF