name: Validate ESPHome Config

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install ESPHome
        run: pip install esphome

      - name: Validate ESPHome configuration
        run: esphome config ./ --validate